name: telemed
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_auth:
  firebase_core:
  firebase_messaging:
  flutter_background: ^1.1.0
  permission_handler: ^11.3.1
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  dropdown_button2: ^2.3.6
  collection: '>=1.16.0'
  livekit_client: 2.1.0
  webview_flutter:
  get: ^4.6.6
#  agora_rtc_engine: 5.2.0
#  livekit_components: 1.2.2+hotfix.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:
  
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
