// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9fq-cSiuclf5gZcdbIGOobmGixJIom4',
    appId: '1:1022131232716:web:aaf8c88a908ff9ce350769',
    messagingSenderId: '1022131232716',
    projectId: 'telemed-project-flutter',
    authDomain: 'telemed-project-flutter.firebaseapp.com',
    storageBucket: 'telemed-project-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQCms1aLvkHZlg377edfc6H_ZhrnK08w',
    appId: '1:1022131232716:android:7a8fc212cbd1dd86350769',
    messagingSenderId: '1022131232716',
    projectId: 'telemed-project-flutter',
    storageBucket: 'telemed-project-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhFbinBVS10d0poSqDb8sp9aWL1_npXI',
    appId: '1:1022131232716:ios:441f50760f0b66dc350769',
    messagingSenderId: '1022131232716',
    projectId: 'telemed-project-flutter',
    storageBucket: 'telemed-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.telemed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhFbinBVS10d0poSqDb8sp9aWL1_npXI',
    appId: '1:1022131232716:ios:441f50760f0b66dc350769',
    messagingSenderId: '1022131232716',
    projectId: 'telemed-project-flutter',
    storageBucket: 'telemed-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.telemed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa9fq-cSiuclf5gZcdbIGOobmGixJIom4',
    appId: '1:1022131232716:web:0d61f96d4a24f0fd350769',
    messagingSenderId: '1022131232716',
    projectId: 'telemed-project-flutter',
    authDomain: 'telemed-project-flutter.firebaseapp.com',
    storageBucket: 'telemed-project-flutter.firebasestorage.app',
  );
}
